-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  mosque_id uuid,
  action character varying NOT NULL,
  table_name character varying,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT audit_logs_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id)
);
CREATE TABLE public.kariah_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  mosque_id uuid NOT NULL,
  ic_passport_number character varying,
  application_reason text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'under_review'::character varying, 'withdrawn'::character varying, 'active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  joined_date date,
  membership_number character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kariah_members_pkey PRIMARY KEY (id),
  CONSTRAINT kariah_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT kariah_members_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT kariah_members_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.khairat_claim_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  claim_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  file_size integer,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT khairat_claim_documents_pkey PRIMARY KEY (id),
  CONSTRAINT khairat_claim_documents_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.khairat_claims(id),
  CONSTRAINT khairat_claim_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.khairat_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid NOT NULL,
  claimant_id uuid,
  title character varying NOT NULL,
  description text NOT NULL,
  requested_amount numeric NOT NULL CHECK (requested_amount > 0::numeric),
  approved_amount numeric CHECK (approved_amount IS NULL OR approved_amount >= 0::numeric),
  status USER-DEFINED DEFAULT 'pending'::claim_status,
  priority USER-DEFINED DEFAULT 'medium'::claim_priority,
  admin_notes text,
  rejection_reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  khairat_member_id uuid,
  claim_id character varying UNIQUE,
  CONSTRAINT khairat_claims_pkey PRIMARY KEY (id),
  CONSTRAINT khairat_claims_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT khairat_claims_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(id),
  CONSTRAINT khairat_claims_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id),
  CONSTRAINT khairat_claims_claimant_id_fkey FOREIGN KEY (claimant_id) REFERENCES public.user_profiles(id),
  CONSTRAINT khairat_claims_khairat_member_id_fkey FOREIGN KEY (khairat_member_id) REFERENCES public.khairat_members(id)
);
CREATE TABLE public.khairat_contributions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contributor_id uuid,
  contributor_name character varying,
  amount numeric NOT NULL,
  payment_method character varying,
  payment_reference character varying,
  status USER-DEFINED DEFAULT 'pending'::contribution_status,
  notes text,
  contributed_at timestamp with time zone DEFAULT now(),
  payment_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  bill_id text,
  mosque_id uuid NOT NULL,
  payment_id character varying UNIQUE,
  CONSTRAINT khairat_contributions_pkey PRIMARY KEY (id),
  CONSTRAINT khairat_contributions_contributor_id_fkey1 FOREIGN KEY (contributor_id) REFERENCES public.user_profiles(id),
  CONSTRAINT khairat_contributions_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id)
);
CREATE TABLE public.khairat_member_dependents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  khairat_member_id uuid NOT NULL,
  full_name character varying NOT NULL,
  relationship character varying NOT NULL,
  ic_passport_number character varying,
  date_of_birth date,
  gender character varying,
  phone character varying,
  email character varying,
  address text,
  emergency_contact boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT khairat_member_dependents_pkey PRIMARY KEY (id),
  CONSTRAINT khairat_member_dependents_khairat_member_id_fkey FOREIGN KEY (khairat_member_id) REFERENCES public.khairat_members(id)
);
CREATE TABLE public.khairat_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  mosque_id uuid NOT NULL,
  ic_passport_number character varying,
  application_reason text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'under_review'::character varying, 'withdrawn'::character varying, 'active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  joined_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  membership_number character varying,
  full_name character varying,
  phone character varying,
  email character varying,
  address text,
  CONSTRAINT khairat_members_pkey PRIMARY KEY (id),
  CONSTRAINT khairat_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT khairat_members_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT khairat_members_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.khairat_payment_receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contribution_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  file_size integer,
  uploaded_by uuid,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT khairat_payment_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT khairat_payment_receipts_contribution_id_fkey FOREIGN KEY (contribution_id) REFERENCES public.khairat_contributions(id),
  CONSTRAINT khairat_payment_receipts_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.legacy_khairat_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mosque_id uuid NOT NULL,
  ic_passport_number character varying NOT NULL,
  full_name character varying NOT NULL,
  address_line1 text,
  address_line2 text,
  address_line3 text,
  invoice_number character varying,
  payment_date date NOT NULL,
  amount numeric NOT NULL,
  payment_method character varying,
  description text,
  customer_po character varying,
  item_number character varying,
  sale_status character varying,
  is_matched boolean DEFAULT false,
  matched_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid NOT NULL,
  contribution_id uuid,
  CONSTRAINT legacy_khairat_records_pkey PRIMARY KEY (id),
  CONSTRAINT legacy_khairat_records_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT legacy_khairat_records_matched_user_id_fkey FOREIGN KEY (matched_user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT legacy_khairat_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.mosque_payment_providers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid NOT NULL,
  provider_type USER-DEFINED NOT NULL,
  is_active boolean DEFAULT true,
  is_sandbox boolean DEFAULT true,
  billplz_api_key text,
  billplz_x_signature_key text,
  billplz_collection_id text,
  chip_brand_id text,
  chip_api_key text,
  stripe_publishable_key text,
  stripe_secret_key text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  toyyibpay_secret_key text,
  toyyibpay_category_code text,
  CONSTRAINT mosque_payment_providers_pkey PRIMARY KEY (id),
  CONSTRAINT mosque_payment_providers_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id)
);
CREATE TABLE public.mosques (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  address text,
  phone character varying,
  email character varying,
  website character varying,
  description text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid UNIQUE,
  is_private boolean DEFAULT false,
  logo_url text,
  banner_url text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  postcode text,
  country text DEFAULT 'Malaysia'::text,
  CONSTRAINT mosques_pkey PRIMARY KEY (id),
  CONSTRAINT mosques_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  mosque_id uuid,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying NOT NULL,
  is_read boolean DEFAULT false,
  action_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT notifications_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id)
);
CREATE TABLE public.organization_people (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid NOT NULL,
  full_name character varying NOT NULL,
  position character varying NOT NULL,
  department character varying,
  email character varying,
  phone character varying,
  address text,
  bio text,
  profile_picture_url text,
  is_public boolean DEFAULT true,
  is_active boolean DEFAULT true,
  start_date date,
  end_date date,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_people_pkey PRIMARY KEY (id),
  CONSTRAINT organization_people_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT organization_people_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.resource_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  parent_id uuid,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resource_categories_pkey PRIMARY KEY (id),
  CONSTRAINT resource_categories_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT resource_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.resource_categories(id)
);
CREATE TABLE public.resources (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid NOT NULL,
  category_id uuid,
  title character varying NOT NULL,
  description text,
  content text,
  file_url text,
  external_url text,
  resource_type character varying,
  language character varying DEFAULT 'en'::character varying,
  tags ARRAY,
  is_featured boolean DEFAULT false,
  is_published boolean DEFAULT false,
  view_count integer DEFAULT 0,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resources_pkey PRIMARY KEY (id),
  CONSTRAINT resources_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id),
  CONSTRAINT resources_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.resource_categories(id),
  CONSTRAINT resources_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.subscription_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid NOT NULL,
  feature_name text NOT NULL,
  usage_count integer DEFAULT 0,
  limit_count integer,
  reset_period text DEFAULT 'monthly'::text,
  last_reset timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_usage_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_usage_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id)
);
CREATE TABLE public.subscription_webhook_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  stripe_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  processed boolean DEFAULT false,
  data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mosque_id uuid,
  key character varying NOT NULL,
  value jsonb NOT NULL,
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_mosque_id_fkey FOREIGN KEY (mosque_id) REFERENCES public.mosques(id)
);
CREATE TABLE public.user_dependents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  full_name character varying NOT NULL,
  relationship character varying NOT NULL,
  date_of_birth date,
  gender character varying,
  phone character varying,
  email character varying,
  address text,
  emergency_contact boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_dependents_pkey PRIMARY KEY (id),
  CONSTRAINT user_dependents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  full_name character varying NOT NULL,
  phone character varying,
  address text,
  account_type USER-DEFINED NOT NULL DEFAULT 'member'::user_account_type,
  membership_type USER-DEFINED DEFAULT 'regular'::membership_type,
  role USER-DEFINED NOT NULL DEFAULT 'member'::user_role,
  status USER-DEFINED NOT NULL DEFAULT 'active'::user_status,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  date_of_birth date,
  gender character varying,
  occupation character varying,
  onboarding_completed boolean DEFAULT false,
  onboarding_completed_at timestamp with time zone,
  profile_picture_url text,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_profile_private boolean DEFAULT false,
  ic_passport_number text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscription_invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'stripe'::text,
  external_invoice_id text,
  stripe_invoice_id text UNIQUE,
  amount_paid integer NOT NULL,
  currency text DEFAULT 'myr'::text,
  status text NOT NULL,
  invoice_url text,
  hosted_invoice_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_subscription_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscription_invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  provider text NOT NULL DEFAULT 'stripe'::text,
  external_customer_id text,
  external_subscription_id text,
  stripe_customer_id text,
  stripe_subscription_id text,
  plan USER-DEFINED NOT NULL DEFAULT 'free'::subscription_plan,
  status USER-DEFINED NOT NULL DEFAULT 'active'::subscription_status,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  canceled_at timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);